# Generated by Django 5.2.4 on 2025-09-15 07:31

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base_app', '0005_article_knowledge_b_title_8da75d_idx'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='ArticleChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(default=None, dimensions=1536, null=True, verbose_name='Векторное представление')),
                ('text', models.TextField(blank=True, verbose_name='Текстовый фрагмент')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_base_app.article', verbose_name='Статья')),
            ],
        ),
    ]
