# Generated by Django 5.2.4 on 2025-09-22 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base_app', '0006_articlechunk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlechunk',
            options={'verbose_name': 'Часть статьи для векторного представления', 'verbose_name_plural': 'Части статьи для векторного представления'},
        ),
        migrations.AddField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL, verbose_name='Автор темы'),
        ),
    ]
