server {
    listen 80;
    charset utf-8;

    access_log /www/app/logs/nginx_access.log;
    error_log /www/app/logs/nginx_error.log error;

    access_log on;

    location / {
        proxy_pass http://knowledge_base_django:8000;
        proxy_set_header X-Url-Scheme $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
    }

    location /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
    alias /www/app/staticfiles/;
}
    location /media/ { root /www/app/; }
}