# Generated by Django 5.2.4 on 2025-09-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Ассистент')], default='user', max_length=10, verbose_name='Роль'),
        ),
    ]
