# Generated by Django 5.2.4 on 2025-09-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_message_options_alter_message_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
