# Generated by Django 5.2.4 on 2025-09-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_userdailytokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailytokens',
            name='tokens_available',
            field=models.PositiveIntegerField(default=35000, verbose_name='Доступные токены'),
        ),
    ]
