# Generated by Django 5.2.4 on 2025-09-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_userdailytokens_tokens_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailytokens',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
