# Generated by Django 5.2.4 on 2025-09-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_alter_userdailytokens_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.AddField(
            model_name='message',
            name='_content',
            field=models.BinaryField(default=b'', verbose_name='Содержимое сообщения'),
            preserve_default=False,
        ),
    ]
