# Generated by Django 5.2.4 on 2025-09-14 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_remove_message_content_message__content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdailytokens',
            options={'verbose_name': 'Токены пользователя', 'verbose_name_plural': 'Токены пользоваетелй'},
        ),
    ]
