# Generated by Django 5.2.4 on 2025-09-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_alter_userdailytokens_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_rag',
            field=models.BooleanField(default=False, verbose_name='Является RAG?'),
        ),
    ]
