# Generated by Django 5.2.4 on 2025-08-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='date_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
