# Generated by Django 5.2.4 on 2025-08-18 13:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_emailconfirmation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmation',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
