# Generated by Django 5.2.4 on 2025-08-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_emailconfirmation_email_in_process_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='confirm_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
